Integrate Google OAuth2 Login with UMich Email
michiganhackers/class-review-frontend pull request #4
Opened 2019-06-23 22:13 UTC by eashwar

# Description

The point of this PR is to integrate Google's OAuth2 login to the WolverineRank app. The login system has been designed such that if you do not login with a G-Suite "umich.edu" email, you will be requested to logout and use one.

# Important Additions

This adds two React components, the `LoginButton` and the `LoginPage`. The `LoginPage` is located at the route `/login` and is the place that Google auth redirects after authentication. It has been added to the `routes.jsx` file accordingly.

The `LoginButton` is a component planned to be part of the global navbar, which not only sports an official "Login with Google" button when logged in, but turns into the "Logout" button when the user is logged in. This is not added to the App anywhere yet, as it is intended to become part of the `Navbar` component which will be added in the future. The `LoginButton` also will insert the user's profile info into the Redux store automatically.

# Notes

This PR adds one `npm` library, `google-auth-library`. Please be sure that you run `yarn` or some equivalent command to make sure you have the library installed.

This PR adds the "Roboto" font for the purposes of styling the "Logout" button to match the premade Google Login button.

2019-06-23 22:26 UTC, eashwar commented
force push as a result of rebasing onto new dev (which had the addition of classpage as well as the security fixes)

2019-06-23 22:33 UTC, eashwar commented
another fpush because i left tokens in the login page and had to rewrite history to hide,

2019-06-27 05:00 UTC, christopherhafke requested changes
Mostly redirects

2019-06-27 05:00 UTC, christopherhafke commented on src/reducers/login_reducers.js
> +                error: null,
Consider removing

2019-06-27 05:00 UTC, christopherhafke commented on src/reducers/login_reducers.js
> +                error: null,
""

2019-06-27 05:00 UTC, christopherhafke commented on src/reducers/login_reducers.js
> +                error: null,
""

2019-06-27 05:00 UTC, christopherhafke commented on src/containers/pages/login_page.jsx
> +        ).catch((err) => console.log(err));
Dispatch error action

2019-06-27 05:00 UTC, christopherhafke commented on src/global_components/login_button.jsx
> +        this.setState({oauth2Client});
Delete this nephew

2019-06-27 05:00 UTC, christopherhafke commented on src/containers/pages/login_page.jsx
> +                window.location = window.location.origin;
Use session storage to store url of where user came from

2019-06-27 05:00 UTC, christopherhafke commented on src/global_components/login_button.jsx
> +        window.location = window.location.origin;
Store url of where user came from in session storage

2019-07-03 03:47 UTC, christopherhafke approved these changes
Looks sweet

2019-07-03 03:47 UTC, christopherhafke commented on src/containers/pages/login_page.jsx
> +            console.log("boop");
Delete this line

2019-07-03 03:48 UTC, merged